#!/usr/bin/env python3
"""
PEFFORT Setup Script - Configurazione Automatica Progetto
Installa venv, dipendenze, e configura le API keys tramite GUI
Eseguire con: python setup_project.py
"""

import os
import sys
import subprocess
import venv
from pathlib import Path
import tkinter as tk
from tkinter import simpledialog, messagebox
import json


class ProjectSetup:
    """Gestisce la configurazione automatica del progetto PEFFORT"""
    
    def __init__(self):
        self.project_root = Path(__file__).parent.resolve()
        self.venv_path = self.project_root / ".venv"
        self.config_path = self.project_root / "config.py"
        self.requirements_path = self.project_root / "requirements.txt"
        self.config_template_path = self.project_root / "config_template.py"
        
    def create_venv(self):
        """Crea la virtual environment se non esiste"""
        if self.venv_path.exists():
            print("✓ Virtual environment già esistente")
            return True
        
        print("📦 Creazione virtual environment...")
        try:
            venv.create(str(self.venv_path), with_pip=True)
            print("✓ Virtual environment creata con successo")
            return True
        except Exception as e:
            messagebox.showerror("Errore", f"Errore nella creazione della venv:\n{e}")
            return False
    
    def get_pip_executable(self):
        """Ritorna il percorso dell'eseguibile pip della venv"""
        if sys.platform == "win32":
            return str(self.venv_path / "Scripts" / "pip.exe")
        else:
            return str(self.venv_path / "bin" / "pip")
    
    def install_requirements(self):
        """Installa le dipendenze da requirements.txt"""
        print("📚 Installazione dipendenze...")
        try:
            pip_exe = self.get_pip_executable()
            subprocess.run(
                [pip_exe, "install", "-r", str(self.requirements_path)],
                check=True,
                capture_output=False
            )
            print("✓ Dipendenze installate con successo")
            return True
        except subprocess.CalledProcessError as e:
            messagebox.showerror("Errore", f"Errore nell'installazione delle dipendenze:\n{e}")
            return False
    
    def show_api_key_dialog(self):
        """Mostra dialog GUI per inserire l'API key MapTiler"""
        root = tk.Tk()
        root.withdraw()  # Nascondi la finestra principale
        root.title("Configurazione PEFFORT")
        
        # Crea una finestra di dialogo personalizzata
        api_key = simpledialog.askstring(
            "MapTiler API Key",
            "Inserisci la tua API key MapTiler:\n\n"
            "(Ottieni una chiave gratuita su https://cloud.maptiler.com/)\n"
            "Se non hai una chiave, puoi lasciarla vuota e aggiornarla dopo.",
            show='*'
        )
        
        root.destroy()
        return api_key if api_key else ""
    
    def create_config_file(self, maptiler_key):
        """Crea il file config.py con le API keys"""
        config_content = f'''# ==============================================================================
# Copyright (c) 2026 Andrea Bonvicin - bFactor Project
# PROPRIETARY LICENSE - TUTTI I DIRITTI RISERVATI
# Sharing, distribution or reproduction is strictly prohibited.
# La condivisione, distribuzione o riproduzione è severamente vietata.
# ==============================================================================

"""
Configuration file for API keys and secrets.
DO NOT COMMIT THIS FILE TO VERSION CONTROL!
This file is listed in .gitignore for security.

Auto-generated by setup_project.py
"""

# MapTiler API Key - Get yours at https://cloud.maptiler.com/
# Sign up for a free account and create an API key
MAPTILER_API_KEY = "{maptiler_key}"

# Mapbox Access Token (optional, for alternative map provider)
# Get yours at https://account.mapbox.com/
MAPBOX_ACCESS_TOKEN = "YOUR_MAPBOX_TOKEN_HERE"


def get_maptiler_key() -> str:
    """Returns the MapTiler API key for 3D map visualization."""
    return MAPTILER_API_KEY


def get_mapbox_token() -> str:
    """Returns the Mapbox access token (optional)."""
    return MAPBOX_ACCESS_TOKEN
'''
        
        try:
            with open(self.config_path, 'w', encoding='utf-8') as f:
                f.write(config_content)
            print(f"✓ File config.py creato: {self.config_path}")
            return True
        except Exception as e:
            messagebox.showerror("Errore", f"Errore nella creazione di config.py:\n{e}")
            return False
    
    def create_launcher_script(self):
        """Crea uno script launcher per avviare il server facilmente"""
        if sys.platform == "win32":
            launcher_path = self.project_root / "run_server.bat"
            launcher_content = r"""@echo off
REM Launcher per il server PEFFORT
setlocal enabledelayedexpansion

REM Attiva la venv
call .venv\Scripts\activate.bat

REM Naviga a webapp e avvia il server
cd webapp
python -m uvicorn app:app --reload --host 0.0.0.0 --port 8001

pause
"""
        else:
            launcher_path = self.project_root / "run_server.sh"
            launcher_content = """#!/bin/bash
# Launcher per il server PEFFORT

# Attiva la venv
source .venv/bin/activate

# Naviga a webapp e avvia il server
cd webapp
python -m uvicorn app:app --reload --host 0.0.0.0 --port 8001
"""
        
        try:
            with open(launcher_path, 'w', encoding='utf-8') as f:
                f.write(launcher_content)
            
            if sys.platform != "win32":
                os.chmod(launcher_path, 0o755)
            
            print(f"✓ Script launcher creato: {launcher_path}")
            return True
        except Exception as e:
            print(f"⚠ Avviso: Errore nella creazione dello script launcher: {e}")
            return True
    
    def ask_start_server(self):
        """Chiede all'utente se vuole avviare il server ora"""
        root = tk.Tk()
        root.withdraw()
        
        result = messagebox.askyesno(
            "Setup Completato",
            "✓ Setup completato con successo!\n\n"
            "Vuoi avviare il server ora?\n"
            "(Il server sarà disponibile su http://localhost:8001)"
        )
        root.destroy()
        return result
    
    def start_server(self):
        """Avvia il server FastAPI"""
        try:
            if sys.platform == "win32":
                python_exe = str(self.venv_path / "Scripts" / "python.exe")
                subprocess.Popen(
                    [python_exe, "-m", "uvicorn", "app:app", "--reload", 
                     "--host", "0.0.0.0", "--port", "8001"],
                    cwd=str(self.project_root / "webapp")
                )
            else:
                python_exe = str(self.venv_path / "bin" / "python")
                subprocess.Popen(
                    [python_exe, "-m", "uvicorn", "app:app", "--reload",
                     "--host", "0.0.0.0", "--port", "8001"],
                    cwd=str(self.project_root / "webapp")
                )
            
            print("✓ Server avviato!")
            print("📱 Accedi a: http://localhost:8001")
            return True
        except Exception as e:
            messagebox.showerror("Errore", f"Errore nell'avvio del server:\n{e}")
            return False
    
    def run(self):
        """Esegue il setup completo"""
        print("\n" + "="*60)
        print("🚀 PEFFORT Setup - Configurazione Progetto")
        print("="*60 + "\n")
        
        # Step 1: Crea venv
        if not self.create_venv():
            return False
        
        # Step 2: Installa dipendenze
        if not self.install_requirements():
            return False
        
        # Step 3: Chiedi API key
        print("\n🔑 Configurazione API keys...")
        api_key = self.show_api_key_dialog()
        
        # Step 4: Crea config.py
        if not self.create_config_file(api_key):
            return False
        
        # Step 5: Crea script launcher
        self.create_launcher_script()
        
        # Step 6: Mostra messaggio di successo
        print("\n" + "="*60)
        print("✅ SETUP COMPLETATO CON SUCCESSO!")
        print("="*60)
        print("\n📋 Prossimi passi:")
        print("1. Per avviare il server, esegui: run_server.bat (Windows)")
        print("   o: ./run_server.sh (Linux/Mac)")
        print("2. Oppure accedi a: http://localhost:8001")
        print("\n")
        
        # Chiedi se avviare il server
        if self.ask_start_server():
            if not self.start_server():
                print("⚠ Impossibile avviare il server automaticamente")
                print("Prova ad avviarlo manualmente usando run_server.bat")
        
        return True


if __name__ == "__main__":
    setup = ProjectSetup()
    success = setup.run()
    sys.exit(0 if success else 1)
